services:
  payload:
    build:
      context: ./payload
      target: builder
    ports:
      - '3000:3000'
    volumes:
      - payload_build:/home/node/app/.next
      - payload_modules:/home/node/app/node_modules
      - assets:/home/node/app/assets
    develop:
      watch:
        - action: sync
          path: ./payload/src
          target: /app/src
          initial_sync: true
        - action: rebuild
          path: ./payload/package.json
        - action: sync+restart
          path: ./payload/next.config.ts
          target: /app/next.config.ts
          initial_sync: true
        - action: sync+restart
          path: ./payload/tsconfig.json
          target: /app/tsconfig.json
          initial_sync: true
    command: sh -c "npm i && npm run dev"
    depends_on:
      mongo:
        condition: service_started
    environment:
      DATABASE_URL: mongodb://mongo/payload
      HOSTNAME: "0.0.0.0"
      PAYLOAD_SECRET: development
    healthcheck: 
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://payload:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 30s
      start_interval: 1s
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
    logging:
      driver: none
  astro:
    build:
      context: ./astro
      target: files
    ports:
      - '4321:4321'
    volumes:
      - assets:/app/public/assets
    command: sh -c "npm i && npm run dev -- --host"
    develop:
      watch:
        - action: sync
          path: ./astro/src
          target: /app/src
          initial_sync: true
        - action: rebuild
          path: ./astro/package.json
        - action: sync+restart
          path: ./astro/astro.config.mjs
          target: /app/astro.config.mjs
          initial_sync: true
        - action: sync+restart
          path: ./astro/tsconfig.json
          target: /app/tsconfig.json
          initial_sync: true
    depends_on:
      payload:
        condition: service_healthy
  build:
    build:
      context: ./astro
      target: builder
    volumes:
      - assets:/home/node/app/public/assets
      - ./build:/home/node/app/dist
    profiles: [build]
    depends_on:
      payload:
        condition: service_healthy
volumes:
  astro_modules:
  payload_modules:
  payload_build:
  mongo-data:
  assets:
