services:
  payload:
    build:
      context: ./payload
      target: builder
    volumes:
      - payload_build:/app/.next
      - payload_modules:/app/node_modules
      - assets:/app/assets
    develop:
      watch:
        - action: sync
          path: ./payload/src
          target: /app/src
          initial_sync: true
        - action: rebuild
          path: ./payload/package.json
        - action: sync+restart
          path: ./payload/next.config.ts
          target: /app/next.config.ts
          initial_sync: true
        - action: sync+restart
          path: ./payload/tsconfig.json
          target: /app/tsconfig.json
          initial_sync: true
    command: sh -c "npm i && npm run dev"
    depends_on:
      mongo:
        condition: service_started
    environment:
      DATABASE_URL: mongodb://mongo/payload
      HOSTNAME: "0.0.0.0"
      PAYLOAD_SECRET: development
    healthcheck: 
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://payload:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 30s
      start_interval: 1s
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
    logging:
      driver: none
  astro:
    build:
      context: ./astro
      target: files
    volumes:
      - assets:/app/public/assets
    command: sh -c "npm i && npm run dev -- --host"
    develop:
      watch:
        - action: sync
          path: ./astro/src
          target: /app/src
          initial_sync: true
        - action: rebuild
          path: ./astro/package.json
        - action: sync+restart
          path: ./astro/astro.config.mjs
          target: /app/astro.config.mjs
          initial_sync: true
        - action: sync+restart
          path: ./astro/tsconfig.json
          target: /app/tsconfig.json
          initial_sync: true
    depends_on:
      payload:
        condition: service_healthy
  build:
    build:
      context: ./astro
      target: builder
    volumes:
      - assets:/home/node/app/public/assets
      - ./build:/home/node/app/dist
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - action: sync+restart
          path: ./astro
          target: /app
          ignore:
            - node_modules/
            - dist/
          initial_sync: true
        - action: sync+exec
          path: ./astro/package.json
          target: /app/package.json
          initial_sync: true
          exec:
            command: sh -c "npm i"
    depends_on:
      payload:
        condition: service_healthy
  legacy:
    build:
      context: ./legacy
      dockerfile_inline: |
        FROM node:25-alpine as base
        FROM base as deps
        WORKDIR /app
        COPY package*.json .
        RUN npm ci
        FROM base as builder
        WORKDIR /app
        COPY --exclude=node_modules/ --exclude=dist/ . .
        COPY --from=deps /app/node_modules ./node_modules
        VOLUME /app/dist
        CMD sh -c "npm run build"
    environment:
      - node_env=development
    volumes:
      - legacy:/app/dist
  caddy:
    image: caddy:latest
    ports:
      - '80:80'
    volumes:
      - ./build:/srv/preview
      - legacy:/srv/legacy
      - caddy_data:/data
    configs:
      - source: caddy
        target: /etc/caddy/Caddyfile
    depends_on:
      legacy:
        condition: service_completed_successfully
      build:
        condition: service_completed_successfully
volumes:
  astro_modules:
  payload_modules:
  payload_build:
  mongo-data:
  assets:
  legacy:
  caddy_data:
configs:
  caddy:
    content: |
      {
        auto_https off
      }
      http://legacy.localhost {
        root /srv/legacy
        file_server
        handle_errors {
          rewrite /index.html
          file_server {
            status 200
          }
        }
      }
      http://cms.localhost {
        reverse_proxy payload:3000
      }
      http://develop.localhost {
        reverse_proxy astro:4321
      }
      http://preview.localhost {
        root /srv/preview
        file_server
        handle_errors {
          rewrite /index.html
          file_server {
            status 200
          }
        }
      }
